config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :documents

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :profile
  belongs_to :document
end

app/models/document.rb
class Document < ApplicationRecord
  validates :name, presence: true
  validates :text, presence: true

  mount_uploader :photo, PhotoUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to documents_path
    else
      render :new
    end
  end

  def show
    @document = Document.find(params[:id])

  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @document = Document.find(params[:id])
    @document.update(document_params)
    redirect_to documents_path
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_path
  end

  private

  def document_params
    params.require(:document).permit(:name, :text, :photo, :photo_cache)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:update, :destroy]

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(current_user.id)
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to profiles_path
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find(current_user.profile.id)
  end

  def update
    @profile.update(profile_params)
      redirect_to profile_path(@profile)
  end

  def destroy
    @profile.destroy
    redirect_to profiles_path
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/edit.html.erb
<h1>Please make your edits</h1>

<%= render "shared/documentform" %>

app/views/documents/index.html.erb
<h1>Documents list</h1>

<%= link_to "New", new_document_path, class: "navbar-wagon-item navbar-wagon-link" %>

<table class="table">
  <thead>
    <tr>
      <th>Document name</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td>
          <%= document.name %>
        </td>
        <td>
          <%= link_to "Show", document_path(document.id), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Edit", edit_document_path(document.id), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Delete", document_path(document.id), method: :delete, class:"navbar-wagon-item navbar-wagon-link", data: {confirm: "Are you sure you want to delete this document?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/new.html.erb
<h1>Start a new document</h1>

<%= render "shared/documentform" %>

app/views/documents/show.html.erb
<h4><%= @document.name %></h4>
<p><%= @document.text %></p>

<%= cl_image_tag @document.photo, { size: '500x500', format: :jpg } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/edit.html.erb
<h1>Please make your edits</h1>

<%= render "shared/profileform" %>

app/views/profiles/index.html.erb
<h1>Profiles list</h1>

<%= link_to "New", new_profile_path, class: "navbar-wagon-item navbar-wagon-link" %>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>User n°</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td>
          <%= profile.first_name %>
        </td>
        <td>
          <%= profile.last_name %>
        </td>
        <td>
          <%= profile.user.id %>
        </td>
        <td>
          <%= link_to "Show", profile_path(profile.id), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Edit", edit_profile_path(profile.id), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Delete", profile_path(profile.id), method: :delete, class:"navbar-wagon-item navbar-wagon-link", data: {confirm: "Are you sure you want to delete this profile?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h1>Start a new profile</h1>

<%= render "shared/profileform" %>

app/views/profiles/show.html.erb
<h1><%= @profile.first_name %> <%= @profile.last_name %></h1>

app/views/shared/_documentform.html.erb
<%= simple_form_for @document do |f| %>
  <%= f.input :name %>
  <%= f.input :text, as: :text, input_html: {rows: 9} %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Documents", documents_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Profiles", profiles_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_profileform.html.erb
<%= simple_form_for @profile do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>